import assert from "node:assert/strict";
import test from "node:test";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const { patchPodfile } = require("./withSentryXcode16Compat.js");

const generatedPodfile = `target 'Yaver' do
  post_install do |installer|
    react_native_post_install(installer)
  end
end
`;

test("adds the Xcode 26 fmt guard to generated Podfiles", () => {
  const patched = patchPodfile(generatedPodfile);
  assert.match(patched, /__apple_build_version__ >= 21000000L/);
  assert.match(patched, /fmt\/include\/fmt\/base\.h/);
});

test("patching a Podfile is idempotent", () => {
  const once = patchPodfile(generatedPodfile);
  assert.equal(patchPodfile(once), once);
});

test("migrates a Podfile that already has the older repair sentinel", () => {
  const existing = generatedPodfile.replace(
    "    react_native_post_install(installer)",
    "    react_native_post_install(installer)\n    # @generated by withSentryXcode16Compat",
  );
  const patched = patchPodfile(existing);
  assert.match(patched, /# @generated by withFmtXcode26Compat-v1/);
  assert.match(patched, /__apple_build_version__ >= 21000000L/);
});
