// Keeps the generated iOS Podfile compatible with Sentry Cocoa 9.10.0 on
// Xcode 16. The ios/ directory is generated/ignored, so the repair belongs in
// an Expo config plugin rather than as a one-off Podfile edit.

const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SENTINEL = "# @generated by withSentryXcode16Compat";

const RUBY_REPAIR = `    ${SENTINEL}
    # Xcode's Objective-C dependency scanner does not inherit Sentry's
    # SWIFT_INCLUDE_PATHS, so explicitly expose the private module map only to
    # the Sentry pod target.
    installer.pods_project.targets.each do |pod_target|
      next unless pod_target.name == 'Sentry'

      pod_target.build_configurations.each do |build_configuration|
        header_paths = build_configuration.build_settings['HEADER_SEARCH_PATHS'] || '$(inherited)'
        private_module_path = '\"\${PODS_TARGET_SRCROOT}/Sources/Sentry/include\"'
        next if header_paths.to_s.include?('Sources/Sentry/include')

        build_configuration.build_settings['HEADER_SEARCH_PATHS'] = "#{header_paths} #{private_module_path}"
      end
    end

    # Swift's CxxStdlib simulator module starts at iOS 16 in Xcode 16. These
    # native targets use Swift/C++ interop, while React Native still advertises
    # iOS 15.1 to pods. Raise only their simulator slices; device/App Store
    # deployment remains at the app's existing floor.
    swift_cxx_targets = %w[NitroModules NitroImage NitroMmkv]
    installer.pods_project.targets.each do |pod_target|
      next unless swift_cxx_targets.include?(pod_target.name)

      pod_target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET[sdk=iphonesimulator*]'] = '16.0'
      end
    end

    # CocoaPods can preserve an umbrella generated for an older React Native
    # install even after the local pod moves to 0.81.5. Remove the obsolete
    # protected-header import only when that header is absent from the
    # installed, authoritative React Native package.
    react_app_delegate_umbrella = File.join(
      installer.sandbox.root,
      'Target Support Files/React-RCTAppDelegate/React-RCTAppDelegate-umbrella.h',
    )
    react_app_delegate_protected_header = File.expand_path(
      '../node_modules/react-native/Libraries/AppDelegate/RCTAppDelegate+Protected.h',
      __dir__,
    )
    if File.exist?(react_app_delegate_umbrella) && !File.exist?(react_app_delegate_protected_header)
      umbrella_source = File.read(react_app_delegate_umbrella)
      stale_import = %Q{#import "RCTAppDelegate+Protected.h"\n}
      if umbrella_source.include?(stale_import)
        File.write(react_app_delegate_umbrella, umbrella_source.sub(stale_import, ''))
      end
    end

    # Sentry 9.10.0 declares this property nullable but implements its setter
    # under NS_ASSUME_NONNULL. Xcode 16 treats that mismatch as an error. The
    # exact-signature guard makes the repair a no-op after an upstream fix.
    sentry_sdk_internal = File.join(
      installer.sandbox.root,
      'Sentry/Sources/Sentry/SentrySDKInternal.m',
    )
    if File.exist?(sentry_sdk_internal)
      sentry_source = File.read(sentry_sdk_internal)
      unfixed_setter = '+ (void)setStartTimestamp:(NSDate *)value'
      fixed_setter = '+ (void)setStartTimestamp:(NSDate * _Nullable)value'
      if sentry_source.include?(unfixed_setter)
        File.chmod(0o644, sentry_sdk_internal) unless File.writable?(sentry_sdk_internal)
        File.write(sentry_sdk_internal, sentry_source.sub(unfixed_setter, fixed_setter))
      end
    end`;

function patchPodfile(contents) {
  if (contents.includes(SENTINEL)) return contents;

  // Expo's generated Podfile closes post_install and then the app target with
  // these final two `end`s. Insert immediately before the post_install close.
  const closingHooks = /\n  end\nend\s*$/.exec(contents);
  if (!closingHooks) {
    throw new Error("Could not find the generated post_install block in ios/Podfile");
  }

  return `${contents.slice(0, closingHooks.index)}\n\n${RUBY_REPAIR}${contents.slice(closingHooks.index)}`;
}

function withSentryXcode16Compat(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      if (!fs.existsSync(podfile)) {
        throw new Error(`Generated Podfile not found at ${podfile}`);
      }
      fs.writeFileSync(podfile, patchPodfile(fs.readFileSync(podfile, "utf8")));
      return cfg;
    },
  ]);
}

module.exports = withSentryXcode16Compat;
module.exports.patchPodfile = patchPodfile;
module.exports.SENTINEL = SENTINEL;
