import { chromium, devices } from '@playwright/test';
import { readFileSync } from 'fs';
const env = Object.fromEntries(readFileSync('.env.test','utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')).trim(),l.slice(l.indexOf('=')+1).trim()]));
const b = await chromium.launch();
const ctx = await b.newContext({ ...devices['iPhone 15'] });
const p = await ctx.newPage();
p.on('pageerror', e => console.log('PAGEERROR:', (e.stack||e.message||'').split('\n').slice(0,6).join('\n')));
await p.goto('http://localhost:8097', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(9000);
const eb = p.getByText(/Continue with Email/i).first();
if (await eb.count()) { await eb.click(); await p.waitForTimeout(3500);
  await p.getByPlaceholder('Email').first().fill(env.YAVER_TEST_EMAIL);
  await p.getByPlaceholder('Password').first().fill(env.YAVER_TEST_PASSWORD);
  await p.getByText(/^Sign In$/).first().click(); await p.waitForTimeout(14000); }
console.log('--- clicking Projects tab ---');
await p.locator('[role=button],button,a').filter({ hasText: /Projects/ }).last().click().catch(e=>console.log('click err', e.message));
await p.waitForTimeout(6000);
console.log('url:', p.url());
await p.waitForTimeout(8000);
console.log('--- /apps screen ---');
console.log((await p.evaluate(()=>document.body.innerText)).slice(0,500).replace(/\n+/g,' | '));
console.log('selects:', await p.locator('select').count(), 'iframes:', await p.locator('iframe').count());
console.log('buttons:', JSON.stringify(await p.locator('[role=button],button').evaluateAll(e=>[...new Set(e.map(x=>(x.textContent||'').trim()).filter(t=>t&&t.length<30))].slice(0,25))));
await b.close();
