import XCTest
@testable import YaverTV

final class CredentialHandoffInteropTests: XCTestCase {
    func testDecryptsDeterministicTypeScriptNaClFixture() throws {
        // Generated by mobile/src/lib/credentialHandoff.ts with fixed keys and
        // nonce. Changing either implementation without the other breaks this.
        let envelope = CredentialHandoffEnvelope(
            version: 1, type: "yaver-credential-envelope", handoffId: "BwcHBwcHBwcHBwcHBwcHBwcH",
            targetDeviceId: "tv_interop_123", accountFingerprint: "j_yeIYsbK1OjVNewRnq1hAbr",
            senderPublicKey: "V9tLNZ8jrl4Ubk4lEgVnBHIlBjSMFQwUdT0Mkz0E1CE=",
            nonce: "BQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUF",
            ciphertext: "Zx4i0UtMN4CyK4/sMlaoUcdrhmFL1aRNvQr50+tSt2vrjtqWwmGGcd4JX4AW9X8333mmPpQ7fyWgbVFkLbdGH6mVZkD+wXMrkCYsJJ4dmwu2URVEBd0EyRkS/Em3T9Ruf/umUlIaCVG5hyDvDTjkiP5P42xLmjC01dgxNYqWvYyWkuC9okAN1w8827wi4jl14IxVOe3vGbWyf6hk8IfMwRXH1eKxAGkbb00bgxGTo4hPWDgN93K8gCjuQq38uM6pbtTMAY9QoZbS9gcD0sbzD+ihe4ZOk/HQ5WvTyWU5ai1H+8yFuvSF5bMgkmcTHpCq8awy2VWnuOzMuliIExcX25Qzc6fw21U=")
        let secret = [UInt8](Data(base64Encoded: "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM=")!)
        let payload = CredentialHandoff.decrypt(envelope: envelope, recipientSecretKey: secret)
        XCTAssertEqual(payload?.kind, "deepseek-api-key")
        XCTAssertEqual(payload?.value, "sk-interoperability-only")
        XCTAssertEqual(payload?.targetDeviceId, "tv_interop_123")
    }

    func testAccountFingerprintMatchesTypeScript() {
        XCTAssertEqual(CredentialHandoff.accountFingerprint("interop-account"), "j_yeIYsbK1OjVNewRnq1hAbr")
    }
}
